### ISSUE TITLE
Schema Registry HTTPS settings

### ISSUE THREAD

**Issue by cricket007** [cricket007/schema-registry-transfer-smt#13]
Haven't used HTTPS on Schema Registry, so configurations / documentation on that are missing.

**Comment by jheinnic** [comment]
For what its worth, our service provider is exposing schema registry over SSL, but is using a certificate that has been signed by a public certificate authority and so is covered by the operating system trust store, such that we've been able to communicate with Schema Registry without setting properties for a custom trust store.

Our provider also use basic HTTP authentication, and we have had some difficulty with using schema-registry-transfer-smt for that reason.  The interesting thing about that issue and this issues is that if you simply need to maintain two sets of the registry schema client's properties as-is, then using a prefix to tell whether a property is for source or destination, then stripping the prefix off as it is being copied would likely solve both Basic HTTP Authentication and SSL configuration.

I am about to submit an Issue and PR that addresses the HTTP authentication, but not as generically as described here.  However, it would be straightforward to replace a small piece of that work with something prefix-based as described here, and the test cases included would continue to work fine as-is.

**Comment by cricket007** [comment]
Is there more to add to this issue or does #15 cover it?

**Comment by jheinnic** [comment]
Hello, there is indeed a little more to adapt #15 to cover this case as well.  Unfortunately there are some runtime issues with #15 that I've been digging into and have not had opportunity to return to this one yet.  As of a few minutes ago I finally see what's going on there and why tests didn't catch the issues.  I believe I can fit a second PR alongside the followup for #15 I'm about to writeup.

The work I was thinking about to address this issue fits in at around lines 99 through 111.  The block that is there now remaps selected properties with either a "src." or "dest." prefix to the same property without the prefix, but in a source-destined or destination-destined HashMap.

When I first wrote this issue, I was contemplating a general look that would check every property for a "src." or "dest." prefix, and on match, remove the prefix to load either the source or destination HashMap, based on which prefix matched.  In hindsight, that would have been problematic when it came to populating the SMT's ConfigDef with specific property contracts.

Since the ConfigDef contract is quite valuable to have, I think that it makes more sense to just add support for additional cherry picked properties, and add more statements like:

```        destProps.put(AbstractKafkaAvroSerDeConfig.BASIC_AUTH_CREDENTIALS_SOURCE,
            config.getString(ConfigName.DEST_BASIC_AUTH_CREDENTIALS_SOURCE));```
(in #configure())

...and...

```                .define(ConfigName.DEST_BASIC_AUTH_CREDENTIALS_SOURCE, ConfigDef.Type.STRING, DEST_BASIC_AUTH_CREDENTIALS_SOURCE_CONFIG_DEFAULT, ConfigDef.Importance.MEDIUM, DEST_BASIC_AUTH_CREDENTIALS_SOURCE_CONFIG_DOC)```
(in static initialization block)

It's easy enough to describe and implement, but I suspect the more challenging detail will be in writing test cases to validate it works.
